### ISSUE TITLE
Web server configuration 

### ISSUE THREAD

**Issue by msmosso** [chrisenytc/emyll#4]
It would be great to have the option to set the default web browser the way you don't need to specify it again.

**Comment by chrisenytc** [comment]
You say standard web browser or default server?

**Comment by msmosso** [comment]
@chrisenytc I mean define a web server to avoid specifying it every time we add a virtualhost, though we already did it at `emyll init`. To be clear, I often have to specify nginx when i run emyll create, but I already defined it using `emyll init`. Got it?

**Comment by chrisenytc** [comment]
I understand. It is an interesting feature. Probably will be implemented soon.
